### ISSUE TITLE
Bridging between two quotient units fails

### ISSUE THREAD

**Issue by mindok** [point85/CaliperSharp#2]
Hi @point85 - thanks for the great library!

I'm doing a bit of work in the mining space and wanting to convert between "grade" units, where a grade is a ratio of two mass units. For example, here in Australia, gold ore grade is expressed as g/t (grams per metric tonne). In some parts of the world it may be expressed as Oz/st (Troy ounces per short ton), or if you want to go really old school, dwt/st (pennyweight per short ton).

If I set up the units in the most obvious way (to me), when I convert between grade units it fails with the following message:

`System.Exception : The unit of measure Type: UNCLASSIFIED, Symbol: g/t, Conversion: g/t, Base Symbol: 1 cannot be converted to Type: UNCLASSIFIED, Symbol: dwt/sh tn, Conversion: dwt/sh tn, Base Symbol: kg/lbm.`

What I thought was the obvious way is:

```csharp
  var uomGrams = sys.GetUOM("g");
  var uomTonnes = sys.GetUOM("t");
  var uomShortTons = sys.GetUOM("sh tn");
  var uomTroyOz = sys.GetUOM("oz t");
  var uomPennyweight = sys.CreateScalarUOM(UnitType.MASS, "pennyweight", "dwt", "Pennyweight");
  uomPennyweight.SetConversion(0.05, uomTroyOz);
  var uomGramsPerTonne = sys.CreateQuotientUOM(uomGrams, uomTonnes);
  var uomPennyweightPerShortTon = sys.CreateQuotientUOM(uomPennyweight, uomShortTons);

  var grade = new Quantity(0.95, uomGramsPerTonne);

  System.Console.WriteLine(grade.Convert(uomPennyweightPerShortTon)); // <-- FAILS HERE
```

If I "force" short tons to convert directly off metric tonnes without bridging via lbm, it all works as expected:
```csharp
...
var uomTonnes = sys.GetUOM("t");
var uomShortTons = sys.GetUOM("sh tn");
var cf = uomShortTons.GetConversionFactor(uomTonnes);
uomShortTons.SetConversion(cf, uomTonnes);
...
```

Is this a limitation in the way quotient based work or am I doing something dumb?

I'll be able to work around it fairly easily - there aren't that many mass & grade units to worry about in practice and in all likelihood we'll need to override built-in conversion factors between metric & customary units anyway (e.g. many gold companies round g/troy oz to 31.10348, rather than 31.1034768).

**Comment by point85** [comment]
Hello Mindok,
Thanks for sending this information.  I will look into the issue and get
back to you.

Regards,
Kent Randall

**Comment by point85** [comment]
This is a bug in how the troy ounce conversion is specified.  In order for a UOM to be converted from one system (e.g. Imperial) to another (e.g. SI), there can be only one bridge unit - in this case it is pound mass to kilogram.  Therefore, all mass units need to specify their conversion with respect to pound mass.  

In MeasurementSystem.cs, please change the SetConversion() code:

```
				case Unit.TROY_OUNCE:
					// troy ounce
					uom = CreateScalarUOM(UnitType.MASS, Unit.TROY_OUNCE, UnitsManager.GetString("troy_oz.name"),
							UnitsManager.GetString("troy_oz.symbol"), UnitsManager.GetString("troy_oz.desc"));
					uom.SetConversion(31.1034768, GetUOM(Unit.GRAM));
					break;
```
					
to:
```
				case Unit.TROY_OUNCE:
					// troy ounce
					uom = CreateScalarUOM(UnitType.MASS, Unit.TROY_OUNCE, UnitsManager.GetString("troy_oz.name"),
							UnitsManager.GetString("troy_oz.symbol"), UnitsManager.GetString("troy_oz.desc"));
					uom.SetConversion(0.06857142857, GetUOM(Unit.POUND_MASS));
					break;
```

					
I will submit this fix to the Git repository.

Also, it is better to use the pre-defined Unit enumerations for getting system-defined UOMs whenever possible instead of the using the UOM symbol.  The enumeration is immutable whereas the symbol can be changed or translated to another language.  Therefore, use GetUOM(Unit.TROY_OUNCE) rather than GetUOM("oz t").

**Comment by mindok** [comment]
Thanks for the rapid response @point85. I tried it out and it works for the scenario above. I think, however, there is still a limitation where quotient units are created from two units with different base units. With the fix above, creating an Oz/tonne grade unit (mixed customary/Troy and metric) breaks in the same way:

```csharp
...
var uomTroyOzPerTonne = sys.CreateQuotientUOM(uomTroyOz, uomTonnes);
...
var grade = new Quantity(0.95, uomGramsPerTonne);
System.Console.WriteLine(grade.Convert(uomTroyOzPerTonne)); // <-- Fails with same error
```
I won't need a change or fix - just pointing it out. I'm happy to submit a PR for the readme & docs to describe the limitation if you like. I suspect removing this limitation would be quite complex and pretty low value as it is easy enough to work around.

> Also, it is better to use the pre-defined Unit enumerations for getting system-defined UOMs whenever possible instead of the using the UOM symbol. The enumeration is immutable whereas the symbol can be changed or translated to another language. Therefore, use GetUOM(Unit.TROY_OUNCE) rather than GetUOM("oz t")

Thanks for the heads up! I had switched to that in my production code. It turns out built-in UoMs don't get created if looked up by symbol and have to be initialised using the Unit enumerations first. I had sidestepped this in my playground area as I had called `var uoms = sys.GetUnitsOfMeasure(UnitType.MASS);` (which initialises all built-ins of that type) before accessing by symbol.

**Comment by point85** [comment]
Before describing this limitation, I will take a deeper look into the issue of converting units of measure from mixed systems.  It is not something that I have considered before.  Is this fairly common in mining and precious metals industry?

**Comment by mindok** [comment]
I dug around quite a few technical reports. The vast majority report grade as g/tonne and contained precious metals as MOz (million Troy Ounces) or kOz. Some report grade as Oz/st (particularly in the US). I only saw one or two mentions of Oz/tonne, and they were in less formal press releases rather than technical reports. So no, not that common!

**Comment by point85** [comment]
Ok. Thanks for the information!

**Comment by point85** [comment]
I did some deeper investigation and I am not able to come up with a generic solution to the issue of converting between units of measure defined with mixed base units, e.g. lbm and kg.  The solution will need to be handled on a case-by-case basis as you have done, or in this case by defining two troy ounce UOMS - one based on a conversion to grams and the second based on conversion to pound mass.  The symbols will need to be unique.  The gram one is used with metric tonne and the pound one with short ton.
